# docker network create mynetwork
# docker run -d --name web1 --net mynetwork jmalloc/echo-server
# docker run -d --name web2 --net mynetwork jmalloc/echo-server
# docker run -d --name web3 --net mynetwork jmalloc/echo-server
# docker run -d --name haproxy --net mynetwork \
#   -v $(pwd):/usr/local/etc/haproxy:ro -p 80:80 haproxytech/haproxy-alpine:2.7

services:
  web1:
    image: jmalloc/echo-server
  web2:
    image: jmalloc/echo-server
  web3:
    image: jmalloc/echo-server

  haproxy:
    image: haproxytech/haproxy-alpine:2.7
    volumes:
      - "./config:/usr/local/etc/haproxy:ro"
    ports:
      - "80:80"
    depends_on:
      - web1
      - web2
      - web3
